### ISSUE TITLE
ERROR:root:--extsize must >= 1!

### ISSUE THREAD

**Issue by zzy1002081237** [kundajelab/ENCODE_chipseq_pipeline#36]

**Comment by leepc12** [comment]
@zzy1002081237: did you get any log for this?

check your `out/qc/rep*/*.cc.qc` on the working directory.
```
$ tail out/qc/rep*/*.cc.qc
```

**Comment by zzy1002081237** [comment]
thanks,I have solved this problem. I found fastq file encoding is Illumna 1.5 , ues seqtk tools  convet it
