### ISSUE TITLE
mm10

### ISSUE THREAD

**Issue by jloupe** [kundajelab/ENCODE_chipseq_pipeline#49]
I tried installing the mm10 genome today and encountered issues retrieving data from http://mitra.stanford.edu/kundaje/genome_data/mm10/. I looked and it appears as though there is no more data here. Have the data for generating genome files been removed?

**Comment by leepc12** [comment]
This pipeline is no longer maintained. Please use a new pipeline https://github.com/ENCODE-DCC/chip-seq-pipeline2.
